### ISSUE TITLE
How do you fetch VTOP Data?

### ISSUE THREAD

**Issue by ryadios** [chaudharydeepanshu/mini_vtop#5]
Is it possible if you could provide an overview on how you fetch the account details?

**Comment by chaudharydeepanshu** [comment]
Delayed reply but posting here for other's future reference.

I didn't require any permission from VIT because the app simply presents the data available in portal in a more accessible way. My project aim was to enhance the usability of older or outdated VIT website without direct access to their data and APIs.

To put it simply, the app utilizes a hidden "webview"(browser) in the background to access the original VTOP website, and serving as a user-friendly interface.

I hope this clarifies. The project was fun to do in my 2nd year DSN.
